{% set name = "xtb" %}
{% set pkg_name = "scine-" + name %}
{% set version = "1.0.1" %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  - url: https://github.com/qcscine/xtb_wrapper/archive/refs/tags/{{ version }}.tar.gz
    sha256: 68d815ebea1953ae9d360099044163ebf1c5da55dffeee1aca276f9b6525d293
    fn: {{ name }}.tar.gz
    patches:
      - pkgconfig.patch
  - url: https://github.com/qcscine/development-utils/archive/refs/tags/4.0.0.tar.gz
    sha256: 54002c2082b6bb75672ec66bf9cf3935bbdf6b085ed9b4d7174cbdedb7c2275d
    fn: dev.tar.gz
    folder: dev

build:
  number: 1
  skip: true  # [win or osx]

  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - boost-cpp
    - eigen
    - libblas
    - scine-utilsos
    - xtb
  run:
    - boost-cpp

test:
  commands:
    - test -f $PREFIX/lib/{{ name }}.module${SHLIB_EXT}

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: |
    Wrapper around xtb to export it into the Scine tool chain.
  home: https://scine.ethz.ch/
  dev_url: https://github.com/qcscine/xtb_wrapper

extra:
  recipe-maintainers:
    - awvwgk
